[project]
name = "rsync-server"
dynamic = ["version"]
description = "A modern lightweight Python wrapper for an rsync daemon."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "buildstamp==0.5.1",
]

[project.scripts]
rsync-server = "main:main"

[dependency-groups]
dev = [
    "build>=1.4.2",
    "ruff>=0.15.10",
    "wheel>=0.46.3",
]

[tool.setuptools.dynamic]
version = {file = "VERSION"}

[tool.setuptools.package-data]
rsync_server = ["_version.json"]

[build-system]
requires = ["setuptools>=64.0", "wheel", "buildstamp"]
build-backend = "buildstamp.backend"

[tool.setuptools.packages.find]
where = ["."]
include = ["rsync_server*"]
